name: CHANNELNET_
parameters:  
  model_name: 
    value: CHANNELNET
  model:
    parameters:
      #General
      in_channels:
        value: 1
      num_classes:
        value: 20
      input_width:
        value: 500
      input_height:
        value: 8
      lr:
        distribution: log_uniform_values
        min: 0.001
        max: 0.008
      one_cycle:
        value: True
      weight_decay:
        min: 0.0001
        max: 0.008

      #Temporal Blocks
      temp_channels: #depth of convolutions in temporal block
        values: [5, 10, 20]
      num_temp_layers: #number of convolutions in temporal block
        values: [2, 4, 6]
      temporal_kernel: #kernel size of temporal convolutions
        value: !!python/tuple [1,33]
      temporal_stride:
        value: !!python/tuple [1,2]
      temporal_dilation_list: #also controls the padding
        value: [!!python/tuple [1,1], !!python/tuple [1,2], !!python/tuple [1,4], !!python/tuple [1,8], !!python/tuple [1,16]]
      
      #Spatial Blocks
      out_channels: #depth of convolutions in spatial block
        values: [4, 8, 16]
      num_spatial_layers: #number of convolutions in spatial block
        values: [2, 3] #leads to kernel sizes [(8,1), (4,1), (2,1)]
      spatial_stride:
        value: !!python/tuple [2,1]
      
      #Residual Blocks
      num_residual_blocks:
        value: 2

      #Convolutional Classifier
      embedding_size: 
        values: [500, 1000]
      down_kernel:
        value: !!python/tuple [1,3]
      down_stride:
        value: 2
      
      #Used for all Modules
      dropout:
        values: [0.2, 0.4, 0.6]
      