name: EEGNet_Embedding
program: train.py
method: random
run_cap: 1
metric:
  goal: maximize
  name: val_acc
parameters:
  model_name: 
    value: EEGNET_Embedding
  final_model:
    value: True
  trainer:
    parameters:
      max_epochs:
        value: 30 
  fine_tuning:
    value: False
  datamodule:
    parameters:
      data_dir: 
        value: "./data/preprocessed/wet/P001"
      test_dir:
        value: "./data/test_sets/sub_P001/wet"
      test_run:
        value: "sub-P001_ses-S003_task-Default_run-003_eeg" #test set
      batch_size:
        value: 128
      num_workers:
        value: 0
      seed:
        value: 42
  model:
    #General
    parameters:
      in_chans: 
        value: 8
      n_classes:
        value: 20
      lr:
        value: 0.00931389991112253
      one_cycle_lr:
        value: True
      weight_decay:
        value: 0.007609794209212413
      input_window_samples:
        value: 500
      final_conv_length:
        value: "auto"
      
      #Convolutional Module
      F1:
        value: 64 
      D:
        value: 2
      kernel_length:
        value: 64 
      pool_mode:
        value: "max"
      drop_prob:
        value: 0.25
      momentum:
        value: 0.1 