name: P004_final
parameters:
  datamodule:
    parameters:
      data_dir: 
        value: "./data/preprocessed/wet/P004"
      val_run: 
        value: "sub-P004_ses-S001_task-Default_run-001_eeg"
      batch_size:
        values: [32, 64, 128]
      num_workers:
        value: 0
      seed:
        value: 42