name: P005_final
parameters:
  datamodule:
    parameters:
      data_dir: 
        value: "./data/preprocessed/wet/P005"
      val_run: 
        value: "sub-P005_ses-S003_task-Default_run-002_eeg"
      batch_size:
        values: [32, 64, 128]
      num_workers:
        value: 0
      seed:
        value: 42