name: P006_final
parameters:
  datamodule:
    parameters:
      data_dir: 
        value: "./data/preprocessed/wet/P006"
      val_run: 
        value: "sub-P006_ses-S006_task-Default_run-003_eeg"
      batch_size:
        values: [32, 64, 128]
      num_workers:
        value: 0
      seed:
        value: 42