program: train.py
method: random
run_cap: 1
metric:
  goal: maximize
  name: val_acc

name: EEGNet_P008_cv
parameters:  
  model_name: 
    value: EEGNET
  trainer:
    parameters:
      max_epochs:
        value: 30 
  datamodule:
    parameters:
      data_dir: 
      #Given a data_dir, do cross_validation by iterating through the dir and select a val run each time
        value: "C:/Users/s_gue/Desktop/master_project/sven-thesis/data/preprocessed/wet/P008"
      val_run:
        value: None #Initialize to None, will be set in the cross_validation script
      batch_size:
        value: 128
      num_workers:
        value: 0
      seed:
        value: 42
  model:
    parameters:
      #General
      in_chans: 
        value: 8
      n_classes:
        value: 20
      lr:
        value: 0.0021981788665798307
      one_cycle_lr:
        value: True
      weight_decay:
        value: 0.006987570819301837
      input_window_samples:
        value: 500
      final_conv_length:
        value: "auto"
      
      #Convolutional Module
      F1:
        value: 64 
      D:
        value: 2
      kernel_length:
        value: 64 
      pool_mode:
        value: "max"
      drop_prob:
        value: 0.25
      momentum:
        value: 0.1 