name: P002
parameters:
  data:
    parameters:
      subject: 
        value: "P002"
      val_run: 
        value: "sub-P002_ses-S006_task-Default_run-003_eeg"
      num_workers:
        value: 0
      seed:
        value: 42