name: P009
parameters:
  data:
    parameters:
      subject: 
        value: "P009"
      val_run: 
        value: "sub-P009_ses-S002_task-Default_run-001_eeg"
      num_workers:
        value: 0
      seed:
        value: 42